openapi: 3.0.0
info:
  title: Blog API
  version: 1.0.0
servers:
  - url: http://blog
    description: Main (production) server
paths:
  /Users:
    post:
      tags:
        - User
      summary: Create user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: A user object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  login:
                    type: string
                  password:
                    type: string
        '422':
          description: Validation errors
